[project]
name = "asn-scrap"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.11.16",
    "bitarray>=3.3.1",
    "lxml>=5.3.2",
    "pandas>=2.2.3",
    "polars>=1.27.0",
    "pyarrow>=19.0.1",
]
